<wsdl:definitions name="HelloService" 
	targetNamespace="http://localhost:8000/helloservice"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

    <wsdl:message name="HelloRequest">
    	<wsdl:part name="firstName" type="xsd:string"/>
    </wsdl:message>

    <wsdl:message name="HelloResponse">
    	<wsdl:part name="message" type="xsd:string"/>
    </wsdl:message>
    <wsdl:portType name="Hello_PortType">
    	<wsdl:operation name="sayHello">
    		<wsdl:input message="HelloRequest"/>
    		<wsdl:output message="HelloResponse"/>
    	</wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="Hello_Binding" type="Hello_PortType">
    	<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    	<wsdl:operation name="sayHello">
    		<soap:operation soapAction="sayHello"/>
    		<wsdl:input>
    			<soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
    		</wsdl:nput>
    		
    		<wsdl:output>
    			<soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
    		</wsdl:output>
    	</wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="Hello_Service">
    	<wsdl:port binding="Hello_Binding" name="Hello_Port">
    		<soap:address location="http://localhost:8000/helloservice"/>
    	</wsdl:port>
    </wsdl:service>
</wsdl:definitions>